site_name: basal
site_url: https://norlandrhagen.github.io/basal/
repo_url: https://github.com/norlandrhagen/basal
repo_name: norlandrhagen/basal

theme:
  name: material
  logo: logo.svg
  favicon: favicon.png
  palette:
    scheme: slate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - markdown-exec

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started: usage.md
  - Discover: discover.md
  - Managing entries: manage.md
  - STAC: stac.md
  - Design: design.md
  - Reference: reference.md
